UPDATE ENC_COL_MAS
   SET COLVAL_EXEC_TYP = 'N'
 WHERE 1=1
--   AND  COL_DATA_TYPE IN ('varchar','nvarchar','char','nchar')
   AND COL_DATA_TYPE IN ('VARCHAR','NVARCHAR','CHAR','NCHAR')
   AND (COL_COMMENT LIKE '%내용%' OR 
        COL_COMMENT LIKE '%명' OR 
        COL_COMMENT LIKE '%설명%' OR 
        COL_COMMENT LIKE '%정보%' OR
        COL_COMMENT LIKE '%비고%' OR
        COL_COMMENT LIKE '%메시지%' OR
        COL_COMMENT LIKE '%메세지%' OR
        COL_COMMENT LIKE '%내역%')
 ;

UPDATE ENC_COL_MAS
SET COLVAL_EXEC_TYP = 'N'
WHERE 1=1
  AND COL_DATA_TYPE IN ( 'TEXT','VARBINARY', 'BIT','XML','NTEXT', 'IMAGE', 'CLOB', 'BLOB')
;

-- 임시, 내역, 로그 테이블 COLVAL 대상 제외
UPDATE ENC_COL_MAS SET COLVAL_EXEC_TYP = 'N'
WHERE TAB_NM IN (
'TB_Partner_20221004',
'TB_PARTNER_210702',
'TB_PARTNER_220708',
'TB_PARTNER_220708_2',
'TB_PARTNER_220712',
'TB_PARTNER_230213'
)

--COL_KIND > 300 대상 중 의미있는 식별번호만 남기고 나머지는 'N' 처리
SELECT COLVAL_EXEC_TYP,COL_DATA_TYPE, (SELECT MAX(TAB_CNT) FROM ENC_TAB_MAS WHERE A.TAB_NM = TAB_NM ),COL_KIND,PK_COL_SEQ,COL_SEQ, MAX_LEN, MIN_COL_VAL, MAX_COL_VAL,TOP_COL_PAT,TAB_NM,COL_NM
FROM ENC_COL_MAS A
WHERE COLVAL_EXEC_TYP = 'Y'
--AND COL_DATA_TYPE IN ('varchar','nvarchar','char','nchar')
AND COL_DATA_TYPE IN ('VARCHAR','NVARCHAR','CHAR','NCHAR')
AND COL_KIND > 200
--AND COL_NM like '%ATER_ID%'
--ORDER BY ISNULL(A.COL_KIND,0) DESC
;

-- 번호, 아이디, 코드, 주소, 사용자, 수신자, 타입등 COLVAL 제외 
UPDATE ENC_COL_MAS
SET COLVAL_EXEC_TYP = 'N'
WHERE COLVAL_EXEC_TYP = 'Y'
AND COL_DATA_TYPE IN ('VARCHAR','NVARCHAR','CHAR','NCHAR')
AND COL_KIND > 200
AND UPPER(COL_NM) NOT LIKE '%NO'
AND UPPER(COL_NM) NOT LIKE '%ID'
AND UPPER(COL_NM) NOT LIKE '%CODE'
AND UPPER(COL_NM) NOT LIKE '%CODE1'
AND UPPER(COL_NM) NOT LIKE '%CODE2'
AND UPPER(COL_NM) NOT LIKE '%IP_ADDRESS'
AND UPPER(COL_NM) NOT LIKE '%TO_ADDRESS'
AND UPPER(COL_NM) NOT LIKE '%USER'
AND UPPER(COL_NM) NOT LIKE '%RECEIVER'
AND UPPER(COL_NM) NOT LIKE '%TYPE'

COMMIT;

-- COL_VAL 대상 확인 
SELECT *
FROM ENC_COL_MAS
WHERE 1=1
AND COLVAL_EXEC_TYP ='Y'


-- COL_VAL날짜 대상 업데이트 
SELECT *
FROM ENC_COL_MAS A
WHERE COL_DATA_TYPE IN ('DATETIME','DATETIME2', 'DATE', 'SMALLDATETIME')

UPDATE ENC_COL_MAS
SET COLVAL_EXEC_TYP = 'A'
WHERE COL_DATA_TYPE IN ('DATETIME','DATETIME2', 'DATE', 'SMALLDATETIME');


--날짜 컬럼 찾기 1
SELECT TOP_COL_PAT
     , MIN_COL_VAL, MAX_COL_VAL, A.*
FROM ENC_COL_MAS A
WHERE 1=1 
AND COLVAL_EXEC_TYP = 'Y'
AND (COL_COMMENT LIKE '%날짜%' 
		OR COL_COMMENT LIKE '%날자%'
		OR COL_COMMENT LIKE '%일자%'
		OR COL_COMMENT LIKE '%일시%'
		OR UPPER(COL_NM) LIKE '%DATE%' 
		OR UPPER(COL_NM) LIKE '%DT%' 
		OR UPPER(COL_NM) LIKE '%TIME%'
		OR UPPER(COL_NM) LIKE '%DTTM%'
		OR UPPER(COL_NM) LIKE '%DTM%'
      OR UPPER(COL_NM) LIKE '%DAY%')
AND COL_DATA_TYPE NOT IN ('DATETIME','DATETIME2', 'DATE','SMALLDATETIME')
AND UPPER(COL_NM) NOT LIKE '%YN'
AND UPPER(COL_NM) NOT LIKE '%REASON'
AND UPPER(COL_NM) NOT LIKE '%DESCR'
AND UPPER(COL_NM) NOT LIKE '%ID'
AND UPPER(COL_NM) NOT LIKE '%NAME'
AND UPPER(COL_NM) NOT LIKE '%NM'
AND UPPER(COL_NM) NOT LIKE '%NO'
AND UPPER(COL_NM) NOT LIKE '%CD'


UPDATE ENC_COL_MAS
SET COLVAL_EXEC_TYP = 'A'
WHERE 1=1 
AND (COL_COMMENT LIKE '%날짜%' OR UPPER(COL_NM) LIKE '%DATE%')
AND COL_DATA_TYPE NOT IN ('DATETIME','DATETIME2', 'DATE','SMALLDATETIME')
AND UPPER(COL_NM) NOT LIKE '%YN'
AND UPPER(COL_NM) NOT LIKE '%REASON';

COMMIT;

--날짜 컬럼 찾기 2
SELECT TOP_COL_PAT
     , MIN_COL_VAL, MAX_COL_VAL, A.*
FROM ENC_COL_MAS A
WHERE 1=1 
AND TOP_COL_PAT IN ( 'NNNNNNNN','NNNNNNNNNNNNNN')
AND TOP_COL_PAT_RT > 50
ORDER BY COL_KIND DESC


--날짜 컬럼 찾아서 업데이트
UPDATE ENC_COL_MAS
SET COLVAL_EXEC_TYP = 'A'
WHERE 1=1 
AND COL_COMMENT LIKE '%날짜%'
AND COL_DATA_TYPE NOT IN ('DATETIME','DATETIME2', 'DATE','SMALLDATETIME');

COMMIT;


--NUMBER타입 : 'B'
SELECT *
FROM ENC_COL_MAS A
WHERE COL_DATA_TYPE IN ('DECIMAL','INT', 'TINYINT', 'NUMERIC', 'BIGINT', 'FLOAT','MONEY', 'SMALLINT')
;

UPDATE ENC_COL_MAS
SET COLVAL_EXEC_TYP = 'B'
WHERE  COL_DATA_TYPE IN ('DECIMAL','INT', 'TINYINT', 'NUMERIC', 'BIGINT', 'FLOAT','MONEY', 'SMALLINT');

COMMIT;



--기타 참고내용--------------------------------------
--COLVAL로직
CASE WHEN COL BETWEEN 1 AND 100 THEN '100이하'
WHEN COL BETWEEN 101 AND 10000 THEN '101~10000'
WHEN COL BETWEEN 10001 AND 100000 THEN '10001~100000'
WHEN COL BETWEEN 100001 AND 1000000 THEN '100001~1000000'
ELSE '10000000초과' END


-- 날짜 컬럼 MIN/MAX 업데이트
--컬럼레벨

UPDATE ENC_COL_MAS
SET MIN_REG_DT = TO_DATE(DATE, MIN_COL_VAL)
   ,MAX_REG_DT = CONVERT(DATE, MAX_COL_VAL)
WHERE COLVAL_EXEC_TYP = 'A' -- 날짜
------------------------------------------------
